//  Review Session Questions 
// Mirrors Test 2 exactly: same question types, same point values
// Section 1: 2 questions  4 pts = 8 pts
// Section 2: 6 questions  4 pts = 24 pts
// Section 3: 13 questions  4 pts = 52 pts
// Section 4: 2 questions  8 pts = 16 pts
// Total: 100 pts

export const REVIEW_QUESTIONS = [
  //  Section 1: Equivalent Fractions (4 pts each) 
  {
    id: "s1q1",
    section: "Section 1",
    sectionTitle: "Equivalent Fractions",
    prompt: "Fill in the blank: 8/9 = ?/27",
    display: "\\frac{8}{9} = \\frac{?}{27}",
    hint: "What do you multiply 9 by to get 27?",
    answer: "24",
    mode: "integer",
    points: 4,
  },
  {
    id: "s1q2",
    section: "Section 1",
    sectionTitle: "Equivalent Fractions",
    prompt: "Fill in the blank: ?/24 = 3/8",
    display: "\\frac{?}{24} = \\frac{3}{8}",
    hint: "What do you multiply 8 by to get 24?",
    answer: "9",
    mode: "integer",
    points: 4,
  },

  //  Section 2: Simplify Fractions (4 pts each) 
  {
    id: "s2q1",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 28/24",
    display: "\\frac{28}{24}",
    hint: "Find the GCD of 28 and 24",
    answer: "7/6",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s2q2",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 4/32",
    display: "\\frac{4}{32}",
    hint: "Find the GCD of 4 and 32",
    answer: "1/8",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s2q3",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 7/0",
    display: "\\frac{7}{0}",
    hint: "What happens when the denominator is 0?",
    answer: "undefined",
    mode: "text",
    points: 4,
  },
  {
    id: "s2q4",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 16/24",
    display: "\\frac{16}{24}",
    hint: "Find the GCD of 16 and 24",
    answer: "2/3",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s2q5",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 0/13",
    display: "\\frac{0}{13}",
    hint: "What is zero divided by any number?",
    answer: "0",
    mode: "integer",
    points: 4,
  },
  {
    id: "s2q6",
    section: "Section 2",
    sectionTitle: "Simplify Fractions",
    prompt: "Simplify: 49/14",
    display: "\\frac{49}{14}",
    hint: "Find the GCD of 49 and 14",
    answer: "7/2",
    mode: "simplified",
    points: 4,
  },

  //  Section 3: Fraction Operations (4 pts each) 
  {
    id: "s3q1",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Multiply and simplify: (5/3)  (7/10)",
    display: "\\frac{5}{3} \\cdot \\frac{7}{10}",
    hint: "Multiply numerators and denominators, then simplify",
    answer: "7/6",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q2",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Multiply and simplify: (14/15)  (3/2)",
    display: "\\frac{14}{15} \\cdot \\frac{3}{2}",
    hint: "Multiply numerators and denominators, then simplify",
    answer: "7/5",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q3",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Divide and simplify: (3/2)  (5/8)",
    display: "\\frac{3}{2} \\div \\frac{5}{8}",
    hint: "Multiply by the reciprocal of the second fraction",
    answer: "12/5",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q4",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Divide and simplify: (5/3)  (9/4)",
    display: "\\frac{5}{3} \\div \\frac{9}{4}",
    hint: "Multiply by the reciprocal of the second fraction",
    answer: "20/27",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q5",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Subtract and simplify: (3/5)  (1/3)",
    display: "\\frac{3}{5} - \\frac{1}{3}",
    hint: "Find a common denominator first",
    answer: "4/15",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q6",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Add and simplify: (1/5) + (2/3)",
    display: "\\frac{1}{5} + \\frac{2}{3}",
    hint: "Find a common denominator first",
    answer: "13/15",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q7",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Subtract and simplify: (3/5)  (3/10)",
    display: "\\frac{3}{5} - \\frac{3}{10}",
    hint: "Find a common denominator first",
    answer: "3/10",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q8",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Subtract and simplify: (5/9)  (7/12)",
    display: "\\frac{5}{9} - \\frac{7}{12}",
    hint: "Find a common denominator first",
    answer: "-1/36",
    mode: "simplified",
    points: 4,
  },
  {
    id: "s3q9",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Multiply: 2  3 (write answer as mixed number)",
    display: "2\\frac{4}{5} \\cdot 3\\frac{2}{7}",
    hint: "Convert to improper fractions, multiply, convert back",
    answer: "9 1/5",
    mode: "mixed",
    points: 4,
  },
  {
    id: "s3q10",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Multiply: (2/3)  3 (write answer as mixed number)",
    display: "\\frac{2}{3} \\cdot 3\\frac{2}{5}",
    hint: "Convert mixed number to improper fraction first",
    answer: "2 4/15",
    mode: "mixed",
    points: 4,
  },
  {
    id: "s3q11",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Subtract: 9  1 (write answer as mixed number)",
    display: "9\\frac{9}{11} - 1\\frac{7}{11}",
    hint: "Subtract whole numbers and fractions separately",
    answer: "8 2/11",
    mode: "mixed",
    points: 4,
  },
  {
    id: "s3q12",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Add: 4 + 7 (write answer as mixed number)",
    display: "4\\frac{1}{2} + 7\\frac{3}{4}",
    hint: "Find a common denominator for the fractions",
    answer: "12 1/4",
    mode: "mixed",
    points: 4,
  },
  {
    id: "s3q13",
    section: "Section 3",
    sectionTitle: "Fraction Operations",
    prompt: "Subtract: 6  3 (write answer as mixed number)",
    display: "6\\frac{1}{4} - 3\\frac{5}{6}",
    hint: "You may need to borrow from the whole number",
    answer: "2 5/12",
    mode: "mixed",
    points: 4,
  },

  //  Section 4: Equations (8 pts each) 
  {
    id: "s4q1",
    section: "Section 4",
    sectionTitle: "Solve Equations",
    prompt: "Solve for x: (5x/4) + 3 = (7x/6)",
    display: "\\frac{5x}{4} + 3 = \\frac{7x}{6}",
    hint: "Multiply everything by the LCM of 4 and 6",
    answer: "36",
    mode: "integer",
    points: 8,
  },
  {
    id: "s4q2",
    section: "Section 4",
    sectionTitle: "Solve Equations",
    prompt: "Solve for y: y/2 = (y/3)  3",
    display: "\\frac{y}{2} = \\frac{y}{3} - 3",
    hint: "Multiply everything by the LCM of 2 and 3",
    answer: "-18",
    mode: "integer",
    points: 8,
  },
];

export const TOTAL_POINTS = REVIEW_QUESTIONS.reduce((s, q) => s + q.points, 0);
